############################################
# LEIA AQUI                                
############################################
# Criado por GUILHERME LAZAROTTO           
# Youtube: www.youtube.com/@guilherme_laz  
# Curso completo: www.curson8n.com.br      
############################################

services:
  waha:
    image: devlikeapro/waha:latest
    platform: linux/amd64
    environment:
      WHATSAPP_HOOK_URL: http://host.docker.internal:5678/webhook/webhook
      WHATSAPP_DEFAULT_ENGINE: WEBJS
      WHATSAPP_HOOK_EVENTS: message.any
      WAHA_NO_API_KEY: true
      WAHA_DASHBOARD_NO_PASSWORD: true
      WHATSAPP_SWAGGER_NO_PASSWORD: true
    volumes:
      - waha_sessions:/app/.sessions
      - waha_media:/app/.media
    ports:
      - "3000:3000"

  n8n:
    image: n8nio/n8n:latest
    platform: linux/amd64
    environment:
      WEBHOOK_URL: http://localhost:5678
      N8N_HOST: localhost:5678
      GENERIC_TIMEZONE: America/Sao_Paulo
      N8N_LOG_LEVEL: debug
      N8N_SECURE_COOKIE: false
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: true
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "5678:5678"

volumes:
  waha_sessions:
  waha_media:
  n8n_data:
